### ISSUE TITLE
Any timeline for CRAN realease?

### ISSUE THREAD

**Issue by AlexPars** [miraisolutions/rTRNG#4]

**Comment by RolandASc** [comment]
Yes, thanks for the interest.

Submission to CRAN is planned for this weekend, so hopefully it will be live at some point next week.

I'll leave this issue open until it is published.

**Comment by riccardoporreca** [comment]
See #5

**Comment by AlexPars** [comment]
Thank you

**Comment by riccardoporreca** [comment]
@AlexPars, rTRNG is on [CRAN](https://cran.r-project.org/package=rTRNG) :tada:
