### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thk686** [miraisolutions/rTRNG#7]
I find the examples given so specific and lacking description that its very difficult to understand why and when one should call jump and split.

1) Perhaps you could give a very simple RcppParallel example of running a single simulation with a single set of fixed parameters and where you simply want valid pseudo-random numbers in each thread.

2) It would also be exceptionally helpful to have a table showing the speed, quality and memory usage of each of the rng engines. Why is yarn2 the only one demonstrated?

Hoping to make some headway using this in RcppParallel.

Thanks.

THK

**Comment by riccardoporreca** [comment]
@thk686, thanks for your interest in and feedback about  **rTRNG**.

In general, what is in fact very specific is how these techniques can be used in real specific parallel / consistent simulation problems. This is why we have included examples to illustrate the core behavior and meaning of _jump_ and _split_ operations, regardless of the specific application context. In this sense the examples are not _specific_ but rather _abstract_. In other words, the purpose is not to tell users _why_ and _when_ to use _jump_ and _split_, but illustrate _what_ they do.

On the other hand, we describe some simple yet  concrete simulation problems in the package vignettes, as well as referring to a full applied example in the package [README](../#readme). Unfortunately, there are no generic solutions to generic problems, although `vignette("mcMat", "rTRNG")` is meant to provide a useful example showing the power of _jump_ and _split_, that would probably apply to quite a few concrete contexts.

We have been using **rTRNG** for several projects and, indeed, the design of the simulation algorithm with _jump_ and _split_ might not be trivial nor unique, also depending on the parallel architecture. We have also been using the library extensively in combination with RcppParallel, which is very natural as you can see from the vignette.

Finally, note that, in terms of the actual random engines, the package simply wraps around the [TRNG](https://github.com/rabauke/trng4) C++ library, hence we defer the user to the TRNG documentation for the details about the engine. The TRNG documentation also includes more examples and extensive benchmarks, so it is intended as the ultimate source of documentation.

As for limiting to one engine (mainly `yarn2`) in the examples, it is just to illustrate the features and concepts that apply to any of the (parallel) engines. Examples with different engines do not add much here, as the goal is not to provide any sort of comparison among them (the full TRNG documentation covers this).

Hope this helps, we are also interested in and curious about other projects using rTRNG, which we could mention to provide other users with more hints and ideas about the practical application of such techniques.

**Comment by riccardoporreca** [comment]
thk686, I coincidentally spotted RcppCore/RcppParallel#98.

From what I see, the RNG part of your problem boils down to a matrix of binomial variates. This seems to suggest that you can indeed use TRNG and RcppParallel in the very same way as shown in [`vignette("mcMat", "rTRNG")`](https://cran.r-project.org/web/packages/rTRNG/vignettes/mcMat.html), where you can just retain the jumping part (splitting is used to possibly simulate a subset of the columns). The source code is in [vignettes/code/mcMatParallel.cpp](../blob/master/vignettes/code/mcMatParallel.cpp).

Note also the other [`vignette("rTRNG.useR2017", "rTRNG")`](https://cran.r-project.org/web/packages/rTRNG/vignettes/rTRNG.useR2017.pdf), which walks through the same example while introducing the package and _jump_ / _split_ operations.

**Comment by thk686** [comment]
Thanks. I'm trying rTRNG on my code.
